using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MiniStore.Domain.Entities;
namespace MiniStore.Infrastructure.Persistence.Configurations;
public sealed class InventoryTrackingBalanceConfiguration:IEntityTypeConfiguration<InventoryTrackingBalance>
{
 public void Configure(EntityTypeBuilder<InventoryTrackingBalance>b){b.ToTable("InventoryTrackingBalances",t=>{t.HasCheckConstraint("CK_InventoryTrackingBalances_Quantity","[Quantity] >= 0");t.HasCheckConstraint("CK_InventoryTrackingBalances_SerialQuantity","[Policy] <> 2 OR [Quantity] IN (0,1)");});b.HasKey(x=>x.Id);b.Property(x=>x.Identifier).HasMaxLength(100).IsRequired();b.Property(x=>x.Quantity).HasPrecision(18,6);b.Property(x=>x.SourceReference).HasMaxLength(100).IsRequired();b.Property(x=>x.RowVersion).IsRowVersion();b.HasIndex(x=>new{x.ProductId,x.Policy,x.Identifier}).IsUnique().HasFilter("[Policy] = 2");b.HasIndex(x=>new{x.ProductId,x.Policy,x.Identifier,x.WarehouseId,x.StorageLocationId}).IsUnique().HasFilter("[Policy] = 1 AND [StorageLocationId] IS NOT NULL");b.HasIndex(x=>new{x.ProductId,x.Policy,x.Identifier,x.WarehouseId}).IsUnique().HasFilter("[Policy] = 1 AND [StorageLocationId] IS NULL");b.HasIndex(x=>new{x.WarehouseId,x.StorageLocationId,x.ExpirationDate});b.HasOne<Product>().WithMany().HasForeignKey(x=>x.ProductId).OnDelete(DeleteBehavior.Restrict);b.HasOne<Warehouse>().WithMany().HasForeignKey(x=>x.WarehouseId).OnDelete(DeleteBehavior.Restrict);b.HasOne<StorageLocation>().WithMany().HasForeignKey(x=>x.StorageLocationId).OnDelete(DeleteBehavior.Restrict);}
}
public sealed class InventoryTrackingTransactionConfiguration:IEntityTypeConfiguration<InventoryTrackingTransaction>
{
 public void Configure(EntityTypeBuilder<InventoryTrackingTransaction>b){b.ToTable("InventoryTrackingTransactions",t=>t.HasCheckConstraint("CK_InventoryTrackingTransactions_Quantity","[Quantity] <> 0 OR [Type] IN (7,8)"));b.HasKey(x=>x.Id);b.Property(x=>x.Identifier).HasMaxLength(100).IsRequired();b.Property(x=>x.Quantity).HasPrecision(18,6);b.Property(x=>x.PickingStrategy).HasConversion<int?>();b.Property(x=>x.SourceReference).HasMaxLength(100).IsRequired();b.Property(x=>x.CreatedByUserId).HasMaxLength(450).IsRequired();b.HasIndex(x=>new{x.ProductId,x.CreatedAt});b.HasIndex(x=>new{x.InventoryTrackingBalanceId,x.CreatedAt});b.HasOne(x=>x.Balance).WithMany().HasForeignKey(x=>x.InventoryTrackingBalanceId).OnDelete(DeleteBehavior.Restrict);b.HasOne<Product>().WithMany().HasForeignKey(x=>x.ProductId).OnDelete(DeleteBehavior.Restrict);b.HasOne<Warehouse>().WithMany().HasForeignKey(x=>x.WarehouseId).OnDelete(DeleteBehavior.Restrict);b.HasOne<StorageLocation>().WithMany().HasForeignKey(x=>x.StorageLocationId).OnDelete(DeleteBehavior.Restrict);}
}
