using MiniStore.Application.DTOs.Purchases;
using MiniStore.Domain.Entities;
using MiniStore.Domain.Interfaces;

namespace MiniStore.Application.Services;
public sealed class PurchaseOrderService(IPurchaseOrderRepository orders,ISupplierQuotationRepository quotations,IPurchaseSourcingRepository sourcing,ISupplierRepository suppliers,IWarehouseRepository warehouses,DocumentNumberService numbers,IUnitOfWork unitOfWork,ICurrentUserService currentUser)
{
 public async Task<List<PurchaseOrderDto>> GetAllAsync(PurchaseOrderStatus? status,string? search){var supplierNames=(await suppliers.GetAllAsync()).ToDictionary(x=>x.Id,x=>x.Name);var warehouseNames=(await warehouses.GetAllAsync()).ToDictionary(x=>x.Id,x=>x.Name);return (await orders.GetAllAsync(status,search)).Select(x=>Map(x,supplierNames.GetValueOrDefault(x.SupplierId,$"#{x.SupplierId}"),warehouseNames.GetValueOrDefault(x.WarehouseId,$"#{x.WarehouseId}"))).ToList();}
 public async Task<int> CreateFromAwardAsync(int sourcingEventId){var award=await quotations.GetAwardAsync(sourcingEventId)??throw new InvalidOperationException("A quotation award is required before creating a purchase order.");var quote=await quotations.GetByIdAsync(award.SupplierQuotationId)??throw new InvalidOperationException("Awarded supplier quotation was not found.");var source=await sourcing.GetByIdAsync(sourcingEventId)??throw new InvalidOperationException("Sourcing event was not found.");if(await orders.GetByQuotationIdAsync(quote.Id)is not null)throw new InvalidOperationException("A purchase order already exists for this quotation.");PurchaseOrder? order=null;await unitOfWork.ExecuteInTransactionAsync(async()=>{var today=DateOnly.FromDateTime(DateTime.Today);order=new PurchaseOrder(await numbers.GenerateAsync(DocumentNumberType.PurchaseOrder,DateTime.Today),source.Id,quote.Id,quote.SupplierId,source.WarehouseId,today,today.AddDays(quote.LeadTimeDays),quote.CurrencyCode,quote.PaymentTermsSnapshot,currentUser.UserId);foreach(var line in quote.Lines){var sourcingLine=source.Lines.Single(x=>x.Id==line.PurchaseSourcingLineId);order.AddLine(new PurchaseOrderLine(line.Id,sourcingLine.ProductId,sourcingLine.MeasurementUnitId,line.QuotedQuantity,sourcingLine.UnitFactorToBase,line.QuotedQuantity*sourcingLine.UnitFactorToBase,line.UnitPrice,line.DiscountPercent,line.TaxPercent,line.ProductCodeSnapshot,line.ProductNameSnapshot,line.UnitNameSnapshot));}await orders.AddAsync(order);});return order!.Id;}
 public async Task ApproveAsync(int id,byte[] rowVersion){var o=await GetTracked(id,rowVersion);await unitOfWork.ExecuteInTransactionAsync(()=>{o.Approve(currentUser.UserId);return Task.CompletedTask;});}
 public async Task ConfirmAsync(int id,byte[] rowVersion){var o=await GetTracked(id,rowVersion);await unitOfWork.ExecuteInTransactionAsync(()=>{o.Confirm(currentUser.UserId);return Task.CompletedTask;});}
 public async Task CancelAsync(int id,string reason,byte[] rowVersion){var o=await GetTracked(id,rowVersion);await unitOfWork.ExecuteInTransactionAsync(()=>{o.Cancel(currentUser.UserId,reason);return Task.CompletedTask;});}
 public async Task<PurchaseOrderDto?> GetAsync(int id){var o=await orders.GetByIdAsync(id);if(o is null)return null;var supplier=await suppliers.GetByIdAsync(o.SupplierId);var warehouse=await warehouses.GetByIdAsync(o.WarehouseId);return Map(o,supplier?.Name??$"#{o.SupplierId}",warehouse?.Name??$"#{o.WarehouseId}");}
 private static PurchaseOrderDto Map(PurchaseOrder o,string supplierName,string warehouseName)=>new(){Id=o.Id,OrderNumber=o.OrderNumber,SupplierName=supplierName,WarehouseName=warehouseName,Status=o.Status,CurrencyCode=o.CurrencyCode,OrderDate=o.OrderDate,ExpectedDate=o.ExpectedDate,RowVersion=o.RowVersion,Lines=o.Lines.Select(l=>new PurchaseOrderLineDto{ProductCode=l.ProductCodeSnapshot,ProductName=l.ProductNameSnapshot,UnitName=l.UnitNameSnapshot,OrderedQuantity=l.OrderedQuantity,UnitPrice=l.UnitPrice,GrossAmount=l.GrossAmount}).ToList()};
 private async Task<PurchaseOrder> GetTracked(int id,byte[] rv){var order=await orders.GetByIdAsync(id)??throw new InvalidOperationException("Purchase order was not found.");if(!order.RowVersion.SequenceEqual(rv))throw new InvalidOperationException("Purchase order was modified by another user. Reload and try again.");return order;}
}
