using MiniStore.Application.DTOs.Purchases;
using MiniStore.Domain.Entities;
using MiniStore.Domain.Interfaces;
namespace MiniStore.Application.Services;
public sealed class PurchaseRequestService(IPurchaseRequestRepository repository,IWarehouseRepository warehouses,IProductRepository products,IMeasurementUnitRepository units,ISupplierRepository suppliers,DocumentNumberService numbers,IUnitOfWork unitOfWork,ICurrentUserService currentUser,PurchaseApprovalService approvals)
{
 public async Task<List<PurchaseRequestDto>> GetAllAsync(PurchaseRequestStatus? status,string? search){var ws=(await warehouses.GetAllAsync()).ToDictionary(x=>x.Id,x=>x.Name);var ps=new Dictionary<int,Product>();var us=new Dictionary<int,MeasurementUnit>();var ss=new Dictionary<int,Supplier>();return (await repository.GetAllAsync(status,search)).Select(x=>Map(x,ws.GetValueOrDefault(x.WarehouseId,"Unknown warehouse"),ps,us,ss)).ToList();}
 public async Task<PurchaseRequestDto?> GetAsync(int id){var r=await repository.GetByIdAsync(id);if(r is null)return null;var ws=await warehouses.GetByIdAsync(r.WarehouseId);var ps=(await products.GetAllAsync(null)).ToDictionary(x=>x.Id);var us=(await units.GetAllAsync()).ToDictionary(x=>x.Id);var ss=(await suppliers.GetAllAsync()).ToDictionary(x=>x.Id);var dto=Map(r,ws?.Name??"Unknown warehouse",ps,us,ss);dto.Approval=await approvals.GetInstanceAsync(id);return dto;}
 public async Task<PurchaseRequestCreatePageDto> GetCreatePageAsync(CreatePurchaseRequestDto? form=null)=>new(){Form=form??new(),Warehouses=(await warehouses.GetAllAsync()).Select(x=>new PurchaseRequestOptionDto(x.Id,x.Name)).ToList(),Products=(await products.GetAllAsync(null)).Where(x=>x.IsActive&&x.ProductType!=ProductType.PreparedToOrder).OrderBy(x=>x.Name).Select(x=>new PurchaseRequestOptionDto(x.Id,$"{x.ProductCode} — {x.Name}")).ToList(),Units=(await units.GetActiveAsync()).OrderBy(x=>x.Dimension).ThenBy(x=>x.Name).Select(x=>new PurchaseRequestOptionDto(x.Id,$"{x.Name} ({x.Symbol}) — {x.Dimension}")).ToList(),Suppliers=(await suppliers.GetAllAsync()).Select(x=>new PurchaseRequestOptionDto(x.Id,x.Name)).ToList()};
 public async Task<int> CreateAsync(CreatePurchaseRequestDto dto,string? sourceType=null,string? sourceReference=null){if(await warehouses.GetByIdAsync(dto.WarehouseId)is null)throw new ArgumentException("Destination warehouse was not found.");if(dto.Lines.Count==0)throw new ArgumentException("A purchase request must contain at least one line.");PurchaseRequest? created=null;await unitOfWork.ExecuteInTransactionAsync(async()=>{if(sourceType is not null&&sourceReference is not null&&await repository.GetActiveBySourceAsync(sourceType,sourceReference)is not null)throw new InvalidOperationException("An open purchase request already exists for this replenishment rule.");created=new PurchaseRequest(await numbers.GenerateAsync(DocumentNumberType.PurchaseRequest,DateTime.Today),dto.WarehouseId,dto.NeededByDate,dto.Priority,dto.Justification,dto.Notes,currentUser.UserId,sourceType,sourceReference);foreach(var line in dto.Lines){var p=await products.GetByIdAsync(line.ProductId)??throw new ArgumentException("Product was not found.");if(!p.IsActive||p.ProductType==ProductType.PreparedToOrder)throw new InvalidOperationException("Purchase requests require an active purchasable product.");var u=await units.GetByIdAsync(line.MeasurementUnitId)??throw new ArgumentException("Measurement unit was not found.");if(!u.IsActive||!p.MeasurementUnitId.HasValue)throw new InvalidOperationException("Product and requested unit must use managed active units.");var stock=await units.GetByIdAsync(p.MeasurementUnitId.Value)??throw new InvalidOperationException("Product stock unit was not found.");if(stock.Dimension!=u.Dimension)throw new InvalidOperationException("Requested unit and product stock unit must use the same measurement dimension.");if(line.SuggestedSupplierId.HasValue&&await suppliers.GetByIdAsync(line.SuggestedSupplierId.Value)is null)throw new ArgumentException("Suggested supplier was not found.");created.AddLine(new PurchaseRequestLine(line.ProductId,line.MeasurementUnitId,line.RequestedQuantity,u.FactorToBaseUnit/stock.FactorToBaseUnit,line.SuggestedSupplierId,line.Notes));}await repository.AddAsync(created);});return created!.Id;}
 public async Task SubmitAsync(int id,byte[] rowVersion){var r=await GetTracked(id,rowVersion);await approvals.SubmitAsync(r);}
 public async Task CancelAsync(int id,string reason,byte[] rowVersion){var r=await GetTracked(id,rowVersion);await unitOfWork.ExecuteInTransactionAsync(async()=>{r.Cancel(currentUser.UserId,reason);await approvals.CancelPendingAsync(id);});}
 private async Task<PurchaseRequest> GetTracked(int id,byte[] rv){var r=await repository.GetByIdAsync(id)??throw new InvalidOperationException("Purchase request was not found.");if(!r.RowVersion.SequenceEqual(rv))throw new InvalidOperationException("Purchase request was modified by another user. Reload and try again.");return r;}
 private static PurchaseRequestDto Map(PurchaseRequest r,string warehouse,IReadOnlyDictionary<int,Product> ps,IReadOnlyDictionary<int,MeasurementUnit> us,IReadOnlyDictionary<int,Supplier> ss)=>new(){Id=r.Id,RequestNumber=r.RequestNumber,WarehouseId=r.WarehouseId,WarehouseName=warehouse,NeededByDate=r.NeededByDate,Priority=r.Priority,Justification=r.Justification,Notes=r.Notes,SourceType=r.SourceType,SourceReference=r.SourceReference,Status=r.Status,CreatedByUserId=r.CreatedByUserId,CreatedAtUtc=r.CreatedAtUtc,RowVersion=r.RowVersion,Lines=r.Lines.Select(x=>new PurchaseRequestLineDto{ProductId=x.ProductId,ProductName=ps.GetValueOrDefault(x.ProductId)?.Name??$"#{x.ProductId}",ProductCode=ps.GetValueOrDefault(x.ProductId)?.ProductCode??"",MeasurementUnitId=x.MeasurementUnitId,UnitName=us.GetValueOrDefault(x.MeasurementUnitId)?.Symbol??$"#{x.MeasurementUnitId}",RequestedQuantity=x.RequestedQuantity,StockQuantity=x.StockQuantity,SuggestedSupplierName=x.SuggestedSupplierId.HasValue?ss.GetValueOrDefault(x.SuggestedSupplierId.Value)?.Name:null,Notes=x.Notes}).ToList(),History=r.History.OrderBy(x=>x.CreatedAtUtc).Select(x=>new PurchaseRequestHistoryDto{FromStatus=x.FromStatus,ToStatus=x.ToStatus,Action=x.Action,UserId=x.UserId,Reason=x.Reason,CreatedAtUtc=x.CreatedAtUtc}).ToList()};
}
