using System.Globalization;using MiniStore.Application.DTOs.Inventory.Replenishment;using MiniStore.Domain.Commands;using MiniStore.Domain.Entities;using MiniStore.Domain.Interfaces;
namespace MiniStore.Application.Services;
public sealed class ReplenishmentService(IReplenishmentRuleRepository rules,IProductRepository products,IWarehouseRepository warehouses,IInventoryBalanceRepository balances,IStockTransferRepository transfers,IStorageLocationRepository locations,IInventoryAccessRepository accessRepository,PutawayRuleService putawayRules,IStockTransferService stockTransfers,IPurchaseRequestRepository purchaseRequests)
{
 public async Task<ReplenishmentPageDto> GetPageAsync(int? warehouseId,string? search,bool exceptionsOnly)
 {
  var ps=await products.GetAllAsync(search);var ws=await warehouses.GetAllAsync();var productMap=ps.ToDictionary(x=>x.Id);var warehouseMap=ws.ToDictionary(x=>x.Id);var bs=(await balances.GetAllAsync()).GroupBy(x=>(x.ProductId,x.WarehouseId)).ToDictionary(x=>x.Key,x=>(OnHand:x.Sum(y=>y.OnHand),Reserved:x.Sum(y=>y.Reserved),Available:x.Sum(y=>y.Available)));
  var approved=await transfers.GetAllAsync(null,StockTransferStatus.Approved);var incoming=approved.SelectMany(x=>x.Items.Select(i=>new{x.ToWarehouseId,i.ProductId,i.Quantity})).GroupBy(x=>(x.ProductId,WarehouseId:x.ToWarehouseId)).ToDictionary(x=>x.Key,x=>x.Sum(y=>y.Quantity));var outgoing=approved.SelectMany(x=>x.Items.Select(i=>new{x.FromWarehouseId,i.ProductId,i.Quantity})).GroupBy(x=>(x.ProductId,WarehouseId:x.FromWarehouseId)).ToDictionary(x=>x.Key,x=>x.Sum(y=>y.Quantity));
  var openRequests=(await purchaseRequests.GetActiveBySourceTypeAsync("ReplenishmentRule")).Where(x=>int.TryParse(x.SourceReference,NumberStyles.None,CultureInfo.InvariantCulture,out _)).ToDictionary(x=>int.Parse(x.SourceReference!,CultureInfo.InvariantCulture));
  var rows=(await rules.GetAllAsync()).Where(x=>productMap.ContainsKey(x.ProductId)&&warehouseMap.ContainsKey(x.WarehouseId)&&(!warehouseId.HasValue||x.WarehouseId==warehouseId)).Select(x=>{var b=bs.GetValueOrDefault((x.ProductId,x.WarehouseId));var inc=incoming.GetValueOrDefault((x.ProductId,x.WarehouseId));var source=x.PreferredSourceWarehouseId.HasValue?bs.GetValueOrDefault((x.ProductId,x.PreferredSourceWarehouseId.Value)).Available:(decimal?)null;var request=openRequests.GetValueOrDefault(x.Id);return new ReplenishmentRowDto{RuleId=x.Id,ProductId=x.ProductId,WarehouseId=x.WarehouseId,Product=productMap[x.ProductId].Name,Warehouse=warehouseMap[x.WarehouseId].Name,SourceWarehouse=x.PreferredSourceWarehouseId.HasValue?warehouseMap.GetValueOrDefault(x.PreferredSourceWarehouseId.Value)?.Name:null,OnHand=b.OnHand,Reserved=b.Reserved,Available=b.Available,ConfirmedIncoming=inc,ConfirmedOutgoing=outgoing.GetValueOrDefault((x.ProductId,x.WarehouseId)),Minimum=x.MinimumQuantity,Maximum=x.MaximumQuantity,SafetyStock=x.SafetyStock,LeadTimeDays=x.LeadTimeDays,SuggestedQuantity=Math.Max(0,x.MaximumQuantity-(b.Available+inc)),SourceAvailable=source,OpenPurchaseRequestId=request?.Id,OpenPurchaseRequestNumber=request?.RequestNumber,IsActive=x.IsActive};}).Where(x=>!exceptionsOnly||x.NeedsReplenishment).OrderByDescending(x=>x.NeedsReplenishment).ThenBy(x=>x.Product).ToList();
  return new ReplenishmentPageDto{Rows=rows,Products=await products.GetAllAsync(null),Warehouses=ws,WarehouseId=warehouseId,Search=search?.Trim()??""};
 }
 public async Task SaveAsync(SaveReplenishmentRuleDto dto)
 {
  _=await products.GetByIdAsync(dto.ProductId)??throw new InvalidOperationException("Product not found.");_=await warehouses.GetByIdAsync(dto.WarehouseId)??throw new InvalidOperationException("Warehouse not found.");if(dto.PreferredSourceWarehouseId.HasValue)_=await warehouses.GetByIdAsync(dto.PreferredSourceWarehouseId.Value)??throw new InvalidOperationException("Source warehouse not found.");
  var rule=await rules.GetAsync(dto.ProductId,dto.WarehouseId);if(rule is null){rule=new ReplenishmentRule(dto.ProductId,dto.WarehouseId,dto.PreferredSourceWarehouseId,dto.MinimumQuantity,dto.MaximumQuantity,dto.SafetyStock,dto.LeadTimeDays);await rules.AddAsync(rule);}else rule.Update(dto.PreferredSourceWarehouseId,dto.MinimumQuantity,dto.MaximumQuantity,dto.SafetyStock,dto.LeadTimeDays);await rules.SaveChangesAsync();
 }
 public async Task SetActiveAsync(int id,bool active){var rule=await rules.GetByIdAsync(id)??throw new InvalidOperationException("Replenishment rule not found.");rule.SetActive(active);await rules.SaveChangesAsync();}

 public async Task<int> CreateTransferDraftAsync(int ruleId,string userId)
 {
  var rule=await rules.GetByIdAsync(ruleId)??throw new InvalidOperationException("Replenishment rule not found.");if(!rule.IsActive)throw new InvalidOperationException("Replenishment rule is inactive.");if(!rule.PreferredSourceWarehouseId.HasValue)throw new InvalidOperationException("A preferred source warehouse is required to create a transfer draft.");
  var product=await products.GetByIdAsync(rule.ProductId)??throw new InvalidOperationException("Product not found.");var source=await warehouses.GetByIdAsync(rule.PreferredSourceWarehouseId.Value)??throw new InvalidOperationException("Source warehouse not found.");var destination=await warehouses.GetByIdAsync(rule.WarehouseId)??throw new InvalidOperationException("Destination warehouse not found.");
  if(source.BranchId.HasValue){var access=await accessRepository.GetBranchAccessAsync(source.BranchId.Value,source.Id);if(access is null||!access.AllowReplenishment||!access.AllowTransferOut)throw new InvalidOperationException("Source warehouse does not allow replenishment transfer-out.");}if(destination.BranchId.HasValue){var access=await accessRepository.GetBranchAccessAsync(destination.BranchId.Value,destination.Id);if(access is null||!access.AllowReplenishment||!access.AllowTransferIn)throw new InvalidOperationException("Destination warehouse does not allow replenishment transfer-in.");}
  var allBalances=await balances.GetAllAsync();decimal Available(int warehouseId)=>allBalances.Where(x=>x.ProductId==rule.ProductId&&x.WarehouseId==warehouseId).Sum(x=>x.Available);
  var approved=await transfers.GetAllAsync(null,StockTransferStatus.Approved);var incoming=approved.Where(x=>x.ToWarehouseId==rule.WarehouseId).SelectMany(x=>x.Items).Where(x=>x.ProductId==rule.ProductId).Sum(x=>x.Quantity);var quantity=Math.Max(0,rule.MaximumQuantity-(Available(rule.WarehouseId)+incoming));if(Available(rule.WarehouseId)+incoming>rule.MinimumQuantity||quantity<=0)throw new InvalidOperationException("This replenishment suggestion is no longer required.");if(Available(source.Id)<quantity)throw new InvalidOperationException("Preferred source warehouse does not have enough available stock.");
  var reference=$"REPLENISHMENT:RULE:{rule.Id}";var open=await transfers.GetAllAsync(reference,null);if(open.Any(x=>x.Reference==reference&&x.Status is StockTransferStatus.Draft or StockTransferStatus.Submitted or StockTransferStatus.Approved))throw new InvalidOperationException("An open transfer already exists for this replenishment rule.");
  int? sourceLocation=null;if(source.RequireSourceLocationForTransfers){var candidates=(await locations.GetWarehouseLocationsAsync(source.Id)).Where(x=>x.Status==StorageLocationStatus.Active&&x.IsPickable).ToDictionary(x=>x.Id);sourceLocation=allBalances.Where(x=>x.ProductId==rule.ProductId&&x.WarehouseId==source.Id&&x.StorageLocationId.HasValue&&candidates.ContainsKey(x.StorageLocationId.Value)&&x.Available>=quantity).OrderBy(x=>source.PickingStrategy==InventoryPickingStrategy.MinimizeLocations?-x.Available:candidates[x.StorageLocationId!.Value].Sequence).Select(x=>x.StorageLocationId).FirstOrDefault();if(!sourceLocation.HasValue)throw new InvalidOperationException("No single pickable source location can cover the suggested quantity.");}
  int? destinationLocation=null;if(destination.RequireDestinationLocationForTransfers){destinationLocation=(await putawayRules.SuggestAsync(product,destination.Id,quantity))?.Id;if(!destinationLocation.HasValue)throw new InvalidOperationException("No eligible destination location can receive the suggested quantity.");}
  return await stockTransfers.CreateAsync(new CreateStockTransferCommand(source.Id,destination.Id,userId,reference,null,[new CreateStockTransferItemCommand(product.Id,quantity,sourceLocation,destinationLocation)]));
 }
}
